version: "3.9"

x-frontend-base: &frontend-base
  container_name: frontend-sb
  build:
    context: .
    dockerfile: apps/frontend/dockerfile
    target: ${BUILD_TARGET:-dev}
  ports:
    - "5010:5010"

services:
  frontend:
    <<: *frontend-base
    profiles: ["prod"]

  frontend-dev:
    <<: *frontend-base
    volumes:
      - type: bind
        source: .
        target: /app
      - fe_node_modules:/app/node_modules
    profiles: ["dev"]

volumes:
  fe_node_modules:
