FROM node:23-slim AS deps
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps/frontend/package.json ./apps/frontend/

RUN corepack enable && yarn install

FROM deps AS dev
CMD ["yarn", "workspace", "sternboats-fe", "start:noopen"]

FROM deps AS prod-build
RUN yarn workspace sternboats-fe build

FROM node:23-slim AS prod
WORKDIR /app

COPY --from=prod-build /app/apps/frontend/dist .

RUN corepack enable && yarn global add serve

EXPOSE 5010
CMD ["serve", "-s", ".", "-l", "5010"]
