const std = @import("std");
const chunk_mod = @import("chunk.zig");
const mesher_mod = @import("mesher.zig");
const world_gen = @import("world_gen.zig");
const Chunk = chunk_mod.Chunk;
const Mesh = mesher_mod.Mesh;

/// Default render distance in chunks (circular radius). Used when neither the
/// `--render-distance=N` CLI flag nor the in-game settings picker overrides it.
/// The runtime value lives on `World.render_distance` (populated from the CLI
/// parse in main.zig and passed through `World.init`). Call sites that
/// previously referenced `RENDER_DISTANCE` have been migrated to either this
/// default (for compile-time allocations / docs) or `world.render_distance`
/// (for anything that should honour the runtime override).
///
/// Scaling note (chunk-size-perf branch, April 2026): this value is
/// *chunks*, not blocks. The visible disc is `DEFAULT_RENDER_DISTANCE × CHUNK_W`
/// blocks across. If you flip `chunk.CHUNK_W`, update this too to preserve
/// the visible world volume — otherwise the player sees a much smaller or
/// much larger fog ring. Currently tuned for CHUNK_W=16 (192-block view),
/// previously 4 at CHUNK_W=48 (192-block view). See
/// `examples/voxel/docs/chunk-size-investigation.md` for the fair
/// comparison that justifies the current pair.
pub const DEFAULT_RENDER_DISTANCE: i32 = 12;

/// Alias for DEFAULT_RENDER_DISTANCE — kept so external docs and legacy call
/// sites that reference `RENDER_DISTANCE` still resolve. New code should use
/// `DEFAULT_RENDER_DISTANCE` or `World.render_distance`.
pub const RENDER_DISTANCE: i32 = DEFAULT_RENDER_DISTANCE;

/// Squared circular radius (in chunks) at which a chunk is eligible to be
/// meshed. Equal to `RENDER_DISTANCE^2`. Matches the disc that
/// `buildSpiralOffsets` lays down for the world-loader, so chunks newly
/// fetched by `World.update` will always pass this gate.
pub const MESH_RADIUS_SQ: i32 = RENDER_DISTANCE * RENDER_DISTANCE;

/// Squared circular radius (in chunks) at which a previously-meshed chunk
/// gets its GPU buffer + host-mesh storage evicted (downgraded back to
/// `.generated`). One chunk wider than the mesh radius — see the hysteresis
/// note below.
///
/// Hysteresis rationale (R = 12):
///   - mesh-eligible: dx² + dz² ≤ 144  (inside the load disc)
///   - evict trigger: dx² + dz² > 169  (i.e. dx² + dz² ≥ 170)
///   - dead zone:     145 ≤ dx² + dz² ≤ 169
///
/// A chunk that drifts from inside the disc out to the dead zone stays
/// meshed but is no longer regenerated by the loader. Only when the player
/// keeps walking and the chunk reaches the evict threshold do we drop the
/// mesh. Coming back in, the chunk only gets re-meshed once it crosses back
/// inside the load disc — so the player has to retreat at least one full
/// chunk past the eviction boundary before any rebuild kicks in. That gap
/// kills the boundary-wobble flicker without holding meshes much longer
/// than necessary.
pub const EVICT_RADIUS_SQ: i32 = (RENDER_DISTANCE + 1) * (RENDER_DISTANCE + 1);

/// Terrain-generation passes per tick during normal gameplay.
///
/// Rationale for K=2: generation is cheap (value noise + a handful of block
/// writes per column, ~1ms/chunk on the bad laptop used for development) and
/// only runs when the player crosses a chunk boundary. Two per tick keeps the
/// async background fill invisible during casual wandering without spiking
/// the frame budget. The pregen phase (loading screen) uses an unbounded
/// budget — see `generateRing` in main.zig.
pub const CHUNKS_PER_TICK: usize = 2;

/// Horizontal pregen radius used by the first-spawn flow.
///
/// Rationale for N = 25 chunks (RADIUS = 2 → 5×5 horizontal ring at the spawn
/// chunk column):
///   - Horizontal movement dominates first-play UX. A player walking in any
///     direction from spawn should not immediately hit an unmeshed edge.
///   - `RENDER_DISTANCE = 4` is a circular cull radius, but only the inner
///     3×3 (9 chunks) need to be MESHED to have a clean view immediately —
///     those are the chunks whose four horizontal neighbours are all also
///     generated. The outer ring (16 chunks) acts as the "generated but not
///     yet meshed" buffer so the inner 9 CAN be meshed without seam holes.
///   - Vertical is free: chunks are 256-tall columns, not 16-tall sections.
///     We don't need a sphere.
///   - A 5×5 square = 25 columns × ~576 KB per chunk ≈ 14 MB RAM. Comfortable.
///     Moving to 7×7 (radius 3, 49 chunks) would push it to ~28 MB and slow
///     the loading screen; not worth it until we palette-compress chunks.
/// Horizontal pregen radius in CHUNKS (not blocks). Like `RENDER_DISTANCE`
/// above, this is chunk-count and needs to track CHUNK_W if you want a
/// stable pregen area. At CHUNK_W=16 we raise this to 6 to keep the spawn
/// ring covering roughly the same 96-block radius the old 2-at-48 pair
/// produced. See `examples/voxel/docs/chunk-size-investigation.md`.
pub const PREGEN_RADIUS: i32 = 6;

/// A RegionAnchor requests that all chunks within RENDER_DISTANCE be loaded.
/// Currently only the player satisfies this. Future entities (beacons, spectators,
/// off-screen simulations) can provide anchors to extend the loaded region.
pub const RegionAnchor = struct {
    position: [3]f32,
};

/// Convert a world-space block coordinate to a chunk-grid coordinate.
pub fn chunkCoordOf(world_coord: i32) i32 {
    return @divFloor(world_coord, chunk_mod.CHUNK_W);
}

pub const ChunkKey = struct {
    cx: i32,
    cz: i32,

    pub const HashContext = struct {
        pub fn hash(_: HashContext, k: ChunkKey) u64 {
            var h = std.hash.Wyhash.init(0);
            h.update(std.mem.asBytes(&k.cx));
            h.update(std.mem.asBytes(&k.cz));
            return h.final();
        }
        pub fn eql(_: HashContext, a: ChunkKey, b: ChunkKey) bool {
            return a.cx == b.cx and a.cz == b.cz;
        }
    };
};

const ChunkOffset = struct { dx: i32, dz: i32 };

pub const ChunkMap = std.HashMap(ChunkKey, *LoadedChunk, ChunkKey.HashContext, std.hash_map.default_max_load_percentage);

/// Pipeline state for a loaded chunk. Generation (writing the block-ID array)
/// and meshing (building a GPU vertex/index buffer) are two distinct phases.
///
/// `.generated`  — `chunk.blocks` is valid in RAM. Deterministic from seed+coords.
///                 No GPU mesh yet. Cannot be meshed until all four horizontal
///                 neighbours are also at least `.generated` (otherwise face
///                 culling against .air for missing neighbours would punch holes
///                 along chunk seams — the classic "sky gap" artifact).
/// `.meshed`     — `mesh.vertices` / `mesh.indices` are valid. Ready to draw.
///
/// Chunks in this codebase are `CHUNK_W × 256 × CHUNK_W` *columns*, not 3D cubes, so there is
/// no vertical neighbour to wait on — a column is meshable as soon as its four
/// horizontal neighbours exist.
pub const ChunkState = enum(u8) {
    generated = 0,
    meshed = 1,
};

/// A single loaded chunk: terrain data + mesh + pipeline state.
pub const LoadedChunk = struct {
    chunk: Chunk,
    mesh: Mesh,
    cx: i32,
    cz: i32,
    /// Pipeline state — generated vs meshed. See `ChunkState` doc above.
    state: ChunkState,
    /// True when the mesh needs full regeneration — either because it has
    /// never been meshed yet, or because a neighbour arrived and the seam
    /// faces need re-evaluation. Only meaningful when `state == .meshed`
    /// except for the initial `true` that lives while `.generated`.
    mesh_dirty: bool,
    /// True when mesh was changed incrementally and GPU buffers need re-upload.
    mesh_incremental_dirty: bool,
    /// True when a neighbour chunk was newly generated, meaning this chunk's
    /// AO samples may have returned `.air` for previously-unloaded neighbours.
    /// Unlike `mesh_dirty` alone, this flag bypasses the `MESH_RADIUS_SQ`
    /// distance gate in the sync mesh loop — chunks in the hysteresis dead zone
    /// (inside eviction radius but outside mesh radius) still get their AO
    /// corrected when the missing neighbour finally loads.
    neighbor_ao_dirty: bool,

    pub fn init(allocator: std.mem.Allocator, cx: i32, cz: i32) LoadedChunk {
        return .{
            .chunk = Chunk.init(allocator),
            .mesh = Mesh.init(allocator),
            .cx = cx,
            .cz = cz,
            .state = .generated,
            .mesh_dirty = true,
            .mesh_incremental_dirty = false,
            .neighbor_ao_dirty = false,
        };
    }

    pub fn deinit(self: *LoadedChunk) void {
        self.mesh.deinit();
        self.chunk.deinit();
    }

    /// Downgrade `.meshed` → `.generated`: release the host-side mesh
    /// allocations and mark the chunk dirty so the next mesh pass that's
    /// allowed to touch it (i.e. once the chunk is back inside the mesh
    /// disc) re-runs `generateMesh` from scratch.
    ///
    /// `chunk.blocks` and `chunk.skylight` are intentionally left untouched
    /// — they're cheap to keep in RAM and expensive to recompute. The whole
    /// point of eviction is to drop the GPU + host *mesh* storage, not the
    /// terrain data.
    ///
    /// GPU buffer destruction lives in main.zig (it owns `chunk_gpu`); the
    /// caller of `evictMesh` is responsible for that side too.
    pub fn evictMesh(self: *LoadedChunk) void {
        self.mesh.freeHostBuffers();
        self.state = .generated;
        self.mesh_dirty = true;
        self.mesh_incremental_dirty = false;
        self.neighbor_ao_dirty = false;
    }

    /// World-space X origin of this chunk in block units.
    pub fn worldX(self: *const LoadedChunk) i32 {
        return self.cx * chunk_mod.CHUNK_W;
    }

    /// World-space Z origin of this chunk in block units.
    pub fn worldZ(self: *const LoadedChunk) i32 {
        return self.cz * chunk_mod.CHUNK_W;
    }

    /// World-space X origin as f32.
    pub fn worldXf(self: *const LoadedChunk) f32 {
        return @as(f32, @floatFromInt(self.worldX()));
    }

    /// World-space Z origin as f32.
    pub fn worldZf(self: *const LoadedChunk) f32 {
        return @as(f32, @floatFromInt(self.worldZ()));
    }
};

pub const World = struct {
    allocator: std.mem.Allocator,
    chunks: ChunkMap,
    /// Runtime-selected render distance in chunks (circular radius). Parsed
    /// from `--render-distance=N` at startup and frozen for the lifetime of
    /// the World — changing it live would require reallocating `spiral_offsets`
    /// and re-evaluating load/unload sets, which the settings menu picker
    /// doesn't need yet. Defaults to DEFAULT_RENDER_DISTANCE (4).
    render_distance: i32,
    /// Pre-computed (dx, dz) offsets sorted by distance from origin (innermost first).
    /// Built once at init; reused every tick.
    spiral_offsets: []ChunkOffset,
    /// World generation config. Determined at init from ACTIVE_PRESET; passed to
    /// every chunk's generateTerrain call. Override individual fields after init
    /// to tweak generation without changing the preset.
    gen_config: world_gen.WorldGenConfig,

    pub fn init(allocator: std.mem.Allocator, preset: world_gen.Preset, render_distance: i32) !World {
        return .{
            .allocator = allocator,
            .chunks = ChunkMap.init(allocator),
            .render_distance = render_distance,
            .spiral_offsets = try buildSpiralOffsets(allocator, render_distance),
            .gen_config = world_gen.presetConfig(preset),
        };
    }

    pub fn deinit(self: *World) void {
        var it = self.chunks.valueIterator();
        while (it.next()) |lc_ptr| {
            lc_ptr.*.deinit();
            self.allocator.destroy(lc_ptr.*);
        }
        self.chunks.deinit();
        self.allocator.free(self.spiral_offsets);
    }

    /// Generate one chunk at (cx, cz) if it does not already exist, and mark
    /// any existing horizontal neighbours as `mesh_dirty` so their seam faces
    /// will be re-evaluated against the new chunk.
    ///
    /// Returns true if a new chunk was created, false if the slot was already
    /// occupied. Cheap to call repeatedly with the same coords.
    pub fn generateChunk(self: *World, cx: i32, cz: i32) !bool {
        const key = ChunkKey{ .cx = cx, .cz = cz };
        if (self.chunks.contains(key)) return false;

        const lc = try self.allocator.create(LoadedChunk);
        lc.* = LoadedChunk.init(self.allocator, cx, cz);
        try lc.chunk.generateTerrain(cx, cz, self.gen_config);
        try self.chunks.put(key, lc);

        // Per-chunk RAM audit — log palette width + byte cost once on first
        // generation so the palette-compression benefit is visible in TAS
        // runs without having to attach a heap profiler. The legacy
        // `[W][H][W]BlockType` layout cost 576 KB flat per chunk regardless
        // of terrain (see `docs/memory.md` §1); the paletted figure varies
        // from ~256 B (uniform chunk) to 576 KB + palette header.
        std.log.info(
            "[CHUNK SIZE] ({d:3},{d:3}) palette_len={d:3} bits={d} block_bytes={d:7} total_bytes={d:7}",
            .{
                cx,
                cz,
                lc.chunk.paletteLen(),
                lc.chunk.bitsPerEntry(),
                lc.chunk.blockDataBytes(),
                lc.chunk.totalBytes(),
            },
        );

        // Mark all 8 surrounding chunks dirty so their seam faces will be
        // re-evaluated against this new neighbour on the next mesh pass.
        //
        // Why diagonals too: AO sampling (both classic and Moore) computes
        // per-vertex brightness by calling `isSolid` at positions ±1 (classic)
        // and ±2 (Moore) from the face plane in the face-parallel axes. A
        // corner vertex on a chunk that shares ONLY a diagonal with the newly
        // loaded chunk will sample positions *inside* that diagonal chunk. If
        // the diagonal chunk was missing when the mesh was first built, those
        // samples returned .air and the corner vertices came out too bright.
        // Dirtying the diagonal here triggers a re-mesh that reads the correct
        // solid/air values once both chunks exist.
        const adjacent = [_]ChunkKey{
            // Face-adjacent
            .{ .cx = cx - 1, .cz = cz },
            .{ .cx = cx + 1, .cz = cz },
            .{ .cx = cx, .cz = cz - 1 },
            .{ .cx = cx, .cz = cz + 1 },
            // Diagonal corners
            .{ .cx = cx - 1, .cz = cz - 1 },
            .{ .cx = cx - 1, .cz = cz + 1 },
            .{ .cx = cx + 1, .cz = cz - 1 },
            .{ .cx = cx + 1, .cz = cz + 1 },
        };
        for (adjacent) |nk| {
            if (self.chunks.get(nk)) |nlc| {
                nlc.mesh_dirty = true;
                nlc.neighbor_ao_dirty = true;
            }
        }
        return true;
    }

    /// True iff `lc` has all four horizontal neighbours generated (or better).
    /// Since chunks here are full-height columns, "all six neighbours" from
    /// classic 3D-chunk voxel engines collapses to four horizontal neighbours.
    /// A chunk must meet this condition before its mesh is built — otherwise
    /// seam faces would cull against `.air` for the missing sides and produce
    /// visible holes along chunk boundaries.
    pub fn hasAllNeighborsGenerated(self: *const World, cx: i32, cz: i32) bool {
        const neighbors = [_]ChunkKey{
            .{ .cx = cx - 1, .cz = cz },
            .{ .cx = cx + 1, .cz = cz },
            .{ .cx = cx, .cz = cz - 1 },
            .{ .cx = cx, .cz = cz + 1 },
        };
        for (neighbors) |nk| {
            if (!self.chunks.contains(nk)) return false;
        }
        return true;
    }

    /// Update chunk loading for the given anchors.
    /// Generates up to CHUNKS_PER_TICK new chunks per call, innermost-first.
    /// Call this from voxelTick once per tick during normal gameplay.
    ///
    /// Meshing is handled separately by the caller — see main.zig's per-tick
    /// mesh loop. The split keeps generation (cheap, deterministic, no GPU
    /// state) completely decoupled from meshing (must wait for neighbours,
    /// produces GPU buffers).
    pub fn update(self: *World, anchors: []const RegionAnchor) !void {
        var loaded_this_tick: usize = 0;

        outer: for (self.spiral_offsets) |off| {
            if (loaded_this_tick >= CHUNKS_PER_TICK) break;

            for (anchors) |anchor| {
                if (loaded_this_tick >= CHUNKS_PER_TICK) break :outer;

                const anchor_cx = chunkCoordOf(@as(i32, @intFromFloat(@floor(anchor.position[0]))));
                const anchor_cz = chunkCoordOf(@as(i32, @intFromFloat(@floor(anchor.position[2]))));
                if (try self.generateChunk(anchor_cx + off.dx, anchor_cz + off.dz)) {
                    loaded_this_tick += 1;
                }
            }
        }
    }

    /// Get a block at world-space coordinates. Returns .air for unloaded chunks.
    pub fn getBlock(self: *const World, wx: i32, wy: i32, wz: i32) chunk_mod.BlockType {
        const cx = chunkCoordOf(wx);
        const cz = chunkCoordOf(wz);
        const lc = self.chunks.get(.{ .cx = cx, .cz = cz }) orelse return .air;
        const lx = wx - cx * chunk_mod.CHUNK_W;
        const lz = wz - cz * chunk_mod.CHUNK_W;
        return lc.chunk.getBlock(lx, wy, lz);
    }

    /// Set a block at world-space coordinates. Returns false if the chunk is unloaded.
    ///
    /// After the mutation, recompute the owning chunk's skylight grid from
    /// scratch and mark the chunk `mesh_dirty` so it is fully re-meshed on the
    /// next tick. Without this step, digging a hole leaves the air cell with
    /// its previous-as-solid `skylight = 0`, and the per-vertex skylight
    /// sampling in the mesher reads that stale 0 — rendering the exposed
    /// floor of the pit nearly black even under direct sunlight. This
    /// replaces the phase-1 "no relight on dig" limitation documented in
    /// `docs/lighting.md`.
    ///
    /// The full-chunk `computeSkylight()` call costs on the order of 30–65 ms
    /// per mutation. We accept that cost here in exchange for guaranteed
    /// correctness — a bounded local BFS would be cheaper but is easy to get
    /// wrong, and click-to-dig is already bottlenecked by the macOS trackpad
    /// latency (80–120 ms) so the extra cost is invisible in practice.
    ///
    /// Cross-chunk skylight propagation is still out of scope (phase-1
    /// limitation): the owning chunk's skylight grid is fully recomputed but
    /// the BFS stops at chunk boundaries, so a dig that opens a sky channel
    /// across a seam will leave the neighbouring chunk with stale light
    /// values. The mesher falls back to the neighbour's own grid via
    /// `BlockGetter.getSkylight`, which gives a near-correct result in most
    /// cases. A future cross-chunk BFS phase would fix the rare divergence.
    ///
    /// Neighbouring mesh dirty-marking: any chunk whose mesh may sample the
    /// modified block (face culling, AO, skylight) is marked `mesh_dirty`.
    /// This covers face-adjacent chunks within AO reach (2 cells) and
    /// diagonal chunks when the modification is within 2 cells of a corner.
    pub fn setBlock(self: *World, wx: i32, wy: i32, wz: i32, block: chunk_mod.BlockType) !bool {
        const cx = chunkCoordOf(wx);
        const cz = chunkCoordOf(wz);
        const lc_ptr = self.chunks.getPtr(.{ .cx = cx, .cz = cz }) orelse return false;
        const lx = wx - cx * chunk_mod.CHUNK_W;
        const lz = wz - cz * chunk_mod.CHUNK_W;
        // Paletted chunk — setBlock can allocate when the palette grows
        // past a power-of-two boundary. Propagate the error instead of
        // swallowing it; OOM here is the caller's problem, not ours.
        try lc_ptr.*.chunk.setBlock(lx, wy, lz, block);
        lc_ptr.*.chunk.computeSkylight();
        // Block light also needs a full recompute: placing a glowstone adds
        // a seed, removing one erases the flood region. Phase 3 keeps this
        // chunk-scoped; cross-chunk block-light seam repair is tracked as
        // the same TODO as skylight's cross-chunk fix.
        lc_ptr.*.chunk.computeBlockLight();
        lc_ptr.*.mesh_dirty = true;

        // Dirty neighbouring chunks whose meshes may reference the modified
        // block. AO (Moore mode) samples up to 2 cells from a face, so any
        // chunk whose edge is within 2 blocks of this position needs a
        // re-mesh to pick up the correct solid/air value.
        const W = chunk_mod.CHUNK_W;
        const R: i32 = 2; // AO sampling reach
        if (lx < R) {
            if (self.chunks.get(.{ .cx = cx - 1, .cz = cz })) |nlc| nlc.mesh_dirty = true;
        }
        if (lx >= W - R) {
            if (self.chunks.get(.{ .cx = cx + 1, .cz = cz })) |nlc| nlc.mesh_dirty = true;
        }
        if (lz < R) {
            if (self.chunks.get(.{ .cx = cx, .cz = cz - 1 })) |nlc| nlc.mesh_dirty = true;
        }
        if (lz >= W - R) {
            if (self.chunks.get(.{ .cx = cx, .cz = cz + 1 })) |nlc| nlc.mesh_dirty = true;
        }
        // Diagonal corners: dirty when within AO reach of both edges at once.
        if (lx < R and lz < R) {
            if (self.chunks.get(.{ .cx = cx - 1, .cz = cz - 1 })) |nlc| nlc.mesh_dirty = true;
        }
        if (lx < R and lz >= W - R) {
            if (self.chunks.get(.{ .cx = cx - 1, .cz = cz + 1 })) |nlc| nlc.mesh_dirty = true;
        }
        if (lx >= W - R and lz < R) {
            if (self.chunks.get(.{ .cx = cx + 1, .cz = cz - 1 })) |nlc| nlc.mesh_dirty = true;
        }
        if (lx >= W - R and lz >= W - R) {
            if (self.chunks.get(.{ .cx = cx + 1, .cz = cz + 1 })) |nlc| nlc.mesh_dirty = true;
        }

        return true;
    }

    /// Get the LoadedChunk containing the given world block coordinate.
    pub fn getChunkAtBlock(self: *World, wx: i32, wz: i32) ?*LoadedChunk {
        return self.chunks.get(.{ .cx = chunkCoordOf(wx), .cz = chunkCoordOf(wz) });
    }

    /// Get the skylight at world-space coordinates. Returns MAX_SKYLIGHT for
    /// any cell above the world top, and also for unloaded chunks.
    ///
    /// Unloaded-chunk default is MAX_SKYLIGHT (not 0): the sky continues
    /// beyond the render boundary, so treating missing neighbours as pitch-black
    /// causes false dark seams along the outer edge of the loaded area. Vertices
    /// at the boundary whose skylight samples fall into an unloaded chunk get
    /// full sunlight instead of artificial shadow. Any in-chunk dimming (caves,
    /// overhangs) only exists in *loaded* terrain and is handled by each chunk's
    /// own skylight grid; we cannot know the state of unloaded terrain, and
    /// "bright unknown" is far less jarring than "dark unknown".
    ///
    /// Note: getBlock returns .air for unloaded chunks (no false AO occlusion).
    /// getBlockLight returns 0 for unloaded chunks (no false emitter glow).
    /// Only skylight uses MAX_SKYLIGHT because it has a global source (the sun).
    pub fn getSkylight(self: *const World, wx: i32, wy: i32, wz: i32) u8 {
        if (wy >= chunk_mod.CHUNK_H) return chunk_mod.MAX_SKYLIGHT;
        const cx = chunkCoordOf(wx);
        const cz = chunkCoordOf(wz);
        const lc = self.chunks.get(.{ .cx = cx, .cz = cz }) orelse return chunk_mod.MAX_SKYLIGHT;
        const lx = wx - cx * chunk_mod.CHUNK_W;
        const lz = wz - cz * chunk_mod.CHUNK_W;
        return lc.chunk.getSkylight(lx, wy, lz);
    }

    /// Get the block-light at world-space coordinates. Returns 0 for any
    /// out-of-world coordinate and for unloaded chunks — block light has no
    /// global seed (unlike the sun) so "unknown" naturally means "no light".
    pub fn getBlockLight(self: *const World, wx: i32, wy: i32, wz: i32) u8 {
        const cx = chunkCoordOf(wx);
        const cz = chunkCoordOf(wz);
        const lc = self.chunks.get(.{ .cx = cx, .cz = cz }) orelse return 0;
        const lx = wx - cx * chunk_mod.CHUNK_W;
        const lz = wz - cz * chunk_mod.CHUNK_W;
        return lc.chunk.getBlockLight(lx, wy, lz);
    }

    /// Returns a BlockGetter backed by this World (queries world coords).
    /// Implements both `getBlock` (for solidity / face culling / physics) and
    /// `getSkylight` (for the mesher's per-vertex skylight sampling).
    pub fn asBlockGetter(self: *const World) chunk_mod.BlockGetter {
        return .{
            .ctx = self,
            .getFn = struct {
                fn get(ctx: *const anyopaque, x: i32, y: i32, z: i32) chunk_mod.BlockType {
                    return @as(*const World, @ptrCast(@alignCast(ctx))).getBlock(x, y, z);
                }
            }.get,
            .getSkylightFn = struct {
                fn getSky(ctx: *const anyopaque, x: i32, y: i32, z: i32) u8 {
                    return @as(*const World, @ptrCast(@alignCast(ctx))).getSkylight(x, y, z);
                }
            }.getSky,
            .getBlockLightFn = struct {
                fn getBl(ctx: *const anyopaque, x: i32, y: i32, z: i32) u8 {
                    return @as(*const World, @ptrCast(@alignCast(ctx))).getBlockLight(x, y, z);
                }
            }.getBl,
        };
    }
};

fn buildSpiralOffsets(allocator: std.mem.Allocator, r: i32) ![]ChunkOffset {
    var offsets = std.ArrayList(ChunkOffset){};
    defer offsets.deinit(allocator);

    var dz: i32 = -r;
    while (dz <= r) : (dz += 1) {
        var dx: i32 = -r;
        while (dx <= r) : (dx += 1) {
            if (dx * dx + dz * dz <= r * r) {
                try offsets.append(allocator, .{ .dx = dx, .dz = dz });
            }
        }
    }

    std.mem.sort(ChunkOffset, offsets.items, {}, struct {
        fn lt(_: void, a: ChunkOffset, b: ChunkOffset) bool {
            return (a.dx * a.dx + a.dz * a.dz) < (b.dx * b.dx + b.dz * b.dz);
        }
    }.lt);

    return offsets.toOwnedSlice(allocator);
}
