#!/bin/bash
# write-overrides.sh: prints overrides.cfg, the settings that belong to one
# target machine, for the installer to read after preseed.cfg.
#
# Where: your computer.
# When:  before each install. serve-preseed.sh (hardware) and test-vm.sh (VM)
#        run it, then serve its output next to preseed.cfg.
# Why:   preseed.cfg holds only the settings that every target machine shares.
#        This script adds the rest: the user, hostname, SSH key and password
#        hash. Hardware and VM installs use the same script, so they cannot
#        differ.
#
# It reads no env file. The script that runs it sets these variables.
# serve-preseed.sh takes them from 2-serve-preseed/<machine>.env.
#
# Required:
#   DEPLOY_USER        the account that gets sudo and the SSH key
#   SERVER_NAME        hostname
#   SSH_PUBKEY_FILE    path to the public key to authorise
#   PASSWORD_CRYPTED   sha512-crypt hash for DEPLOY_USER (openssl passwd -6)
#
# Optional:
#   CONSOLE            serial console device, e.g. ttyAMA0. test-vm.sh sets it
#                      so the install is visible and logged. Do not set it for
#                      hardware: the target machine has no serial port, and the screen
#                      stays black for the whole install.
set -euo pipefail

need() {
    local name="$1"
    [ -n "${!name:-}" ] || { echo "write-overrides.sh: $name is required" >&2; exit 1; }
}

need DEPLOY_USER
need SERVER_NAME
need SSH_PUBKEY_FILE
need PASSWORD_CRYPTED

[ -f "$SSH_PUBKEY_FILE" ] \
    || { echo "write-overrides.sh: no such public key: $SSH_PUBKEY_FILE" >&2; exit 1; }

PUBKEY="$(cat "$SSH_PUBKEY_FILE")"

cat <<EOF
# GENERATED by scripts/write-overrides.sh. Layered over preseed.cfg via
# preseed/include - later values win. Do not edit; edit the generator.
d-i passwd/username string $DEPLOY_USER

# These two are BELIEVED NOT TO TAKE EFFECT and nothing may depend on them -
# REQ-SERVER-004, #285. This file is fetched over the network, so netcfg has
# already run and already picked a hostname before it is read; see the long
# note in preseed.cfg. They are kept because they cost nothing and are correct
# if this preseed is ever driven from a local file instead.
#
# What binds is netcfg/hostname= on the KERNEL COMMAND LINE (the caller's job -
# scripts/lib.sh installer_params(), scripts/test-vm/test-vm.sh), and the late_command below.
d-i netcfg/get_hostname string $SERVER_NAME
d-i netcfg/hostname string $SERVER_NAME

# The password hash is injected rather than committed. The previous generation
# shipped 'password changeme' in the clear in a public repository for nine
# months; this generation's preseed.cfg holds no hash at all.
d-i passwd/user-password-crypted password $PASSWORD_CRYPTED
EOF

if [ -n "${CONSOLE:-}" ]; then
    echo "d-i debian-installer/add-kernel-opts string console=$CONSOLE,115200n8"
fi

cat <<EOF

# Only ONE late_command may exist across all included files - last wins,
# silently - so it is defined here and nowhere else. EXTEND it; never add a
# second one anywhere.
#
# The first three commands impose the hostname on the installed filesystem -
# REQ-SERVER-004, #285. This is the layer that is guaranteed, as opposed to the
# netcfg/* keys above (read too late) and the boot-line key (right, but only
# provable on hardware). It works because of where late_command sits in the
# finish-install sequence:
#
#   netcfg runs -> /etc/hostname and /etc/hosts are written from whatever it
#   decided -> base-installer copies them into /target -> pkgsel ->
#   finish-install.d/07 (THIS) -> finish-install.d/55netcfg-copy-config.
#
# So the target's identity files already exist when this runs, and the only
# netcfg script that runs afterwards is 55netcfg-copy-config, which writes
# interface configuration into netplan/NetworkManager/ifupdown and does not
# touch /etc/hostname or /etc/hosts. Nothing overwrites what is set here.
#
# The 127.0.1.1 line is REPLACED, not appended to: netcfg writes its own, and
# on the failing install that line read '127.0.1.1 192.168.1.182 192'. The grep
# pattern leaves the dots unescaped on purpose - backslashes inside a debconf
# value that is already using line continuations are a needless risk, and an
# anchored '^127.0.1.1' cannot plausibly match anything else in /etc/hosts.
#
# A space separates the fields rather than a tab, for the same reason: no
# backslash escape has to survive debconf. /etc/hosts is whitespace-delimited,
# and postinstall.sh's repair matches either.
d-i preseed/late_command string \\
    echo '$SERVER_NAME' > /target/etc/hostname; \\
    grep -v '^127.0.1.1' /target/etc/hosts > /target/etc/hosts.new; \\
    echo '127.0.1.1 $SERVER_NAME' >> /target/etc/hosts.new; \\
    mv /target/etc/hosts.new /target/etc/hosts; \\
    in-target mkdir -p /home/$DEPLOY_USER/.ssh; \\
    echo '$PUBKEY' > /target/home/$DEPLOY_USER/.ssh/authorized_keys; \\
    in-target chown -R $DEPLOY_USER:$DEPLOY_USER /home/$DEPLOY_USER/.ssh; \\
    in-target chmod 700 /home/$DEPLOY_USER/.ssh; \\
    in-target chmod 600 /home/$DEPLOY_USER/.ssh/authorized_keys; \\
    echo '$DEPLOY_USER ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/90-$DEPLOY_USER; \\
    chmod 440 /target/etc/sudoers.d/90-$DEPLOY_USER
EOF
