#!/bin/bash
# write-overrides.sh - emit overrides.cfg on stdout.
#
# The preseed is architecture- and host-neutral by construction (REQ-EMU-005);
# everything specific to one run is layered over it through preseed/include.
# This script is the ONE generator of that layer, called by both the VM harness
# and the metal path, so a VM run and a real install cannot drift apart.
#
# It used to be a function inside vm/test-vm.sh, which meant the metal path had
# no way to produce the same file without copying it.
#
# Required in the environment:
#   DEPLOY_USER        the account that gets sudo and the SSH key
#   SERVER_NAME        hostname
#   SSH_PUBKEY_FILE    path to the public key to authorise
#   PASSWORD_CRYPTED   sha512-crypt hash for DEPLOY_USER (openssl passwd -6)
#
# Optional:
#   CONSOLE            serial console device, e.g. ttyAMA0. Set by the VM
#                      harness so the install is watchable and the boot is
#                      logged. MUST be left unset on real hardware: pointing
#                      the kernel console at a serial port a laptop does not
#                      have means a black screen for the whole install.
set -euo pipefail

need() {
    local name="$1"
    [ -n "${!name:-}" ] || { echo "write-overrides.sh: $name is required" >&2; exit 1; }
}

need DEPLOY_USER
need SERVER_NAME
need SSH_PUBKEY_FILE
need PASSWORD_CRYPTED

[ -f "$SSH_PUBKEY_FILE" ] \
    || { echo "write-overrides.sh: no such public key: $SSH_PUBKEY_FILE" >&2; exit 1; }

PUBKEY="$(cat "$SSH_PUBKEY_FILE")"

cat <<EOF
# GENERATED by scripts/write-overrides.sh. Layered over preseed.cfg via
# preseed/include - later values win. Do not edit; edit the generator.
d-i passwd/username string $DEPLOY_USER
d-i netcfg/get_hostname string $SERVER_NAME
d-i netcfg/hostname string $SERVER_NAME

# The password hash is injected rather than committed. The previous generation
# shipped 'password changeme' in the clear in a public repository for nine
# months; this generation's preseed.cfg holds no hash at all.
d-i passwd/user-password-crypted password $PASSWORD_CRYPTED
EOF

if [ -n "${CONSOLE:-}" ]; then
    echo "d-i debian-installer/add-kernel-opts string console=$CONSOLE,115200n8"
fi

cat <<EOF

# Only ONE late_command may exist across all included files - last wins,
# silently - so it is defined here and nowhere else.
d-i preseed/late_command string \\
    in-target mkdir -p /home/$DEPLOY_USER/.ssh; \\
    echo '$PUBKEY' > /target/home/$DEPLOY_USER/.ssh/authorized_keys; \\
    in-target chown -R $DEPLOY_USER:$DEPLOY_USER /home/$DEPLOY_USER/.ssh; \\
    in-target chmod 700 /home/$DEPLOY_USER/.ssh; \\
    in-target chmod 600 /home/$DEPLOY_USER/.ssh/authorized_keys; \\
    echo '$DEPLOY_USER ALL=(ALL) NOPASSWD:ALL' > /target/etc/sudoers.d/90-$DEPLOY_USER; \\
    chmod 440 /target/etc/sudoers.d/90-$DEPLOY_USER
EOF
