FROM oven/bun:latest AS deps
WORKDIR /app
COPY apps/seanscards/backend/package.json  apps/seanscards/tsconfig.json ./
COPY apps/seanscards/backend ./src
COPY apps/seanscards/configs.ts ./configs.ts
RUN bun install --production

FROM deps AS dev
CMD ["bun", "--hot", "--no-clear-screen", "/app/src/index.ts"]

FROM deps AS prod
RUN bun build ./src/index.ts --target=bun --outfile ./dist/index.js
CMD ["bun", "./dist/index.js"]
