FROM node:23-slim AS deps
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps/seanscards/package.json ./apps/seanscards/package.json
COPY apps/seanscards/frontend ./apps/seanscards/frontend
COPY apps/seanscards/tsconfig.json ./apps/seanscards/tsconfig.json
COPY apps/seanscards/configs.ts ./apps/seanscards/configs.ts

RUN corepack enable && yarn install

FROM deps AS dev
CMD ["yarn", "workspace", "seanscards-fe", "start:noopen"]

FROM deps AS prod-build
RUN yarn workspace seanscards-fe build

FROM node:23-slim AS prod
WORKDIR /app
COPY --from=prod-build /app/apps/seanscards/frontend/dist .
RUN npm install -g serve
CMD ["serve", "-s", ".", "-l", "4243"]
