FROM node:20 as deps
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn
COPY apps/seanscards/package.json ./apps/seanscards/package.json
COPY apps/seanscards/frontend ./apps/seanscards/frontend
COPY apps/seanscards/tsconfig.json ./apps/seanscards/tsconfig.json
COPY apps/seanscards/configs.ts ./apps/seanscards/configs.ts

RUN corepack enable && yarn install

FROM deps as dev
CMD ["yarn", "workspace", "seanscards-fe", "start:noopen"]

FROM deps as prod-build
RUN yarn workspace seanscards-fe run build
FROM prod-build as prod
COPY ./apps/seanscards/frontend/dist /app
WORKDIR /app
CMD ["yarn", "dlx", "serve", "-s", ".", "-l", "4243"]
