version: "3.9"

services:
    # We don't strictly need container_name, it just makes the docker env cleaner.
    # We know we don't need to scale this. docker by default adds an index,
    # in case you DID want to scale it.
  frontend:
    container_name: frontend
    build:
      context: ../..
      dockerfile: apps/seanscards/frontend/dockerfile
      target: ${BUILD_TARGET:-dev}
    ports:
      - "4243:4243"

  frontend-dev:
    extends:
      service: frontend
    volumes:
      - type: bind
        source: ../..
        target: /app
      - fe_node_modules:/app/node_modules
    profiles: ["dev"]

  backend:
    container_name: backend
    build:
      context: ../..
      dockerfile: apps/seanscards/backend/dockerfile
      target: ${BUILD_TARGET:-dev}
    ports:
      - "4244:4244"
    volumes:
      - sqlite_data:/app/db
    environment:
      - DB_PATH=/app/db
    command: ${BACKEND_CMD:-bun --hot --no-clear-screen /app/src/index.ts}
    networks:
      default:
        aliases:
          - seanscards.localhost/api

volumes:
  sqlite_data:
  fe_node_modules:
