FROM oven/bun:latest AS deps
WORKDIR /app
COPY apps/planning-poker/backend/package.json .
COPY apps/planning-poker/configs.ts ./configs.ts
RUN bun install --production

FROM deps AS dev
CMD ["bun", "--hot", "--no-clear-screen", "/app/src/index.ts"]

FROM deps AS prod-build
COPY apps/planning-poker/backend ./src
RUN bun build ./src/index.ts --target=bun --outfile ./dist/index.js

FROM oven/bun:latest AS prod
WORKDIR /app
COPY --from=prod-build /app/dist ./dist
CMD ["bun", "./dist/index.js"]
